module.exports = {
  allSame: require('./allSame'),
  centroid: require('./centroid'),
  clamp: require('./clamp'),
  color: require('./color'),
  colorMirror: require('./colorMirror'),
  dimensions: require('./dimensions'),
  distance: require('./distance'),
  lerp: require('./lerp'),
  padColor: require('./padColor'),
  pointOnLine: require('./pointOnLine'),
  pythagoreanA: require('./pythagoreanA'),
  rgbFromHex: require('./rgbFromHex'),
  rise: require('./rise'),
  roundPlaces: require('./roundPlaces'),
  run: require('./run'),
  slope: require('./slope'),
  surroundingPoints: require('./surroundingPoints'),
  tableValues: require('./tableValues'),
  timeMirror: require('./timeMirror')
};
